#!/bin/python3
x=0
y=0
a = list(map(int, input().rstrip().split()))

b = list(map(int, input().rstrip().split()))

for i in range(0,3):
    if a[i]>b[i]:
        x=x+1
    elif a[i]<b[i]:
        y=y+1
    else:
        x=x
        y=y
print(x,y)
