#!/bin/python3
count=0
x=int(input())
print("enter the list of space separated input")
print("this is done in another branch in git")

y = list(map(int, input('Enter numbers: ').split()))
print(y)
for i in y:
    count=count+i
print(count)
